version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  # php用コンテナ
  php:
    container_name: php
    build:
      context: ./php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql

  #MySQL用コンテナ
  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysq
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test

  #phpMyAdmin用コンテナ
  phpmyadmin:
    container_name: phpMyAdmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    restart: always
    ports:
      - "80:80"

#  #cronコンテナ
#  cron:
#    container_name: cron
#    tty: true
#    build:
#      context: ./cron
#      dockerfile: ./Dockerfile
#    volumes:
#      - ./src:/var/www/html
#    depends_on:
#      - php